// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./AboutHero")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact: dynamic(() => import("./Contact")),
  faqs: dynamic(() => import("./Faqs")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  industries: dynamic(() => import("./Industries")),
  our_works: dynamic(() => import("./OurWorks")),
  services: dynamic(() => import("./Services")),
  technologies: dynamic(() => import("./Technologies")),
  training: dynamic(() => import("./Training")),
};
