import { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Geozone",
  description: "Generated by create next app",
};
const heading = localFont({
  src: "../public/fonts/headingFont.woff2",
  variable: "--font-heading",
});

const body = localFont({
  src: "../public/fonts/bodyFont.woff2",
  variable: "--font-body",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${heading.variable} ${body.variable} overflow-x-hidden`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
